### ISSUE TITLE
Noise in script tag

### ISSUE THREAD

**Issue by zadro** [Kub-AT/php-simple-html-dom-parser#4]
When attempting to parse all Heading tags of certain sites, there's an opening Heading tag in script data, and forceTagsClosed doesn't seem to apply.

How to avoid this H tag parsing in the script tag? 

Example site: techcrunch dot com with H2 wrapped in script tags.

find('H2') for the above site example collects garbage.

Amazing script, btw! Please advise.

**Comment by Kub-AT** [comment]
Hi, I am not author, just using external library "PHP Simple HTML DOM Parser" hosted on Sourceforge
With all bugs or feature requests you should go there https://sourceforge.net/projects/simplehtmldom/
