### ISSUE TITLE
set MAX_FILE_SIZE

### ISSUE THREAD

**Issue by haziri** [Kub-AT/php-simple-html-dom-parser#7]
Hi, i got problem when reading site that has large html code. I found out that you can set the MAX_FILE_SIZE. Now i change it directly in vendors folder and i can read the site again. Can you make a config file that i can set in app/config/

Thank you,.

**Comment by Kub-AT** [comment]
@haziri or maybe it is enough to define the MAX_FILE_SIZE constant before running the script?
